#!/bin/sh -x
g++ $@ -Wall /home/animesh/Desktop/SUDOKU/SUDOKU_sem1/simplecpp/lib/libsprite.a -I/home/animesh/Desktop/SUDOKU/SUDOKU_sem1/simplecpp/include -I/usr/include/X11 -L/usr/X11R6/lib -lX11 -std=c++11
